var main = document.getElementById("maindiv");
main.classList.add("maindiv");
var leftdiv = document.createElement("div");
main.appendChild(leftdiv);
leftdiv.classList.add("leftdiv");
var image = document.createElement("img");
image.src = ("image.png");
image.classList.add("img");
leftdiv.appendChild(image);
var head1 = document.createElement("h2");
head1.innerHTML = "V.GayathriDevi";
leftdiv.appendChild(head1);
var para = document.createElement("p");
para.innerHTML = "Trainer cum Developer";
leftdiv.appendChild(para);
var horizontal = document.createElement("hr");
leftdiv.appendChild(horizontal);
var para1 = document.createElement("p");
para1.innerHTML = "Father name:satyanarayana.v";
leftdiv.appendChild(para1);
var para2 = document.createElement("p");
para2.innerHTML = "gmail id:gayathriv410@gmail.com";
leftdiv.appendChild(para2);
var para3 = document.createElement("p");
para3.innerHTML = "Mobile no:7730807897";
leftdiv.appendChild(para3);
var para4 = document.createElement("p");
para4.innerHTML = "Address:Hyderabad";
leftdiv.appendChild(para4);

var rightdiv = document.createElement("div");
main.appendChild(rightdiv);
rightdiv.classList.add("rightdiv");
var head2 = document.createElement("h1");
head2.innerHTML = "Carrier Objective";
rightdiv.appendChild(head2);
var para = document.createElement("p");
para.innerHTML = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
rightdiv.appendChild(para);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para1 = document.createElement("p");
para1.innerHTML = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
rightdiv.appendChild(para1);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para2 = document.createElement("p");
para2.innerHTML = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
rightdiv.appendChild(para2);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para3 = document.createElement("p");
para3.innerHTML = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
rightdiv.appendChild(para3);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para4 = document.createElement("p");
para4.innerHTML = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";
rightdiv.appendChild(para4);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para5 = document.createElement("p");
para5.innerHTML = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
rightdiv.appendChild(para5);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para6 = document.createElement("p");
para6.innerHTML = "gggggggggggggggggggggggggggggggggggggggggggggggggggggggg";
rightdiv.appendChild(para6);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para7 = document.createElement("p");
para7.innerHTML = "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh";
rightdiv.appendChild(para7);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para8 = document.createElement("p");
para8.innerHTML = "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii";
rightdiv.appendChild(para8);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para9 = document.createElement("p");
para9.innerHTML = "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj";
rightdiv.appendChild(para9);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para10 = document.createElement("p");
para10.innerHTML = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk";
rightdiv.appendChild(para10);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
var para11 = document.createElement("p");
para11.innerHTML = "lllllllllllllllllllllllllllllllllllllllllllllllllllllllll";
rightdiv.appendChild(para11);
var horizontal = document.createElement("hr");
rightdiv.appendChild(horizontal);
